version: "3.3"
services:
  php-laravel-webcrawler:
    container_name: php-laravel-webcrawler
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4040:80
    volumes:
      - ./:/var/www/html
